version: '3.8'

services:
  web:
    image: nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-web
    ports:
      - "80:80"
    restart: always
    volumes:
      #conf files
      - ./nginx/conf:/etc/nginx/conf.d:ro
      #log files
      - ./nginx/log:/var/log/nginx
      #       Mount source-code for development
      - ../:/app
    links:
      - php
    depends_on:
      - php
      - db
      - redis
      - memcached
  php:
    #    image: php:7.4-fpm
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: always
    volumes:
      - ./php/conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ../:/app
  composer:
    image: composer
    volumes:
      - ../:/app
    command: install
  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD : ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE : ${MARIADB_DATABASE}
      MARIADB_USER : ${MARIADB_USER}
      MARIADB_PASSWORD : ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/db/mysql:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
      - ./mariadb/conf:/etc/mysql/conf.d:ro
  myadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY : 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    restart: always
    depends_on:
      - db
    links:
      - db
  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    ports:
      - "6379:6379"
    restart: always
  memcached:
    image: memcached
    container_name: ${COMPOSE_PROJECT_NAME}-memcached
    ports:
      - "11211:11211"
    restart: always